# Generated by Django 5.0.4 on 2024-05-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitae', '0003_aluno_genero_alter_professor_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='genero',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, default='', upload_to='alunos'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.ImageField(blank=True, default='', upload_to='professores'),
        ),
    ]
