# Generated by Django 5.0.4 on 2024-05-10 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitae', '0004_remove_aluno_genero_remove_professor_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='ano',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='uc',
            name='acronimo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='EquipaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vitae.professor')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vitae.uc')),
            ],
        ),
        migrations.AddConstraint(
            model_name='equipadocente',
            constraint=models.UniqueConstraint(fields=('uc', 'professor'), name='unique_equipe_docente'),
        ),
    ]
