# Generated by Django 5.0.4 on 2024-05-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitae', '0006_alter_uc_coordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codificado',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
