# Generated by Django 5.0.4 on 2024-05-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitae', '0006_alter_uc_coordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='acronimo',
            field=models.CharField(max_length=4, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
