# Generated by Django 5.0.4 on 2024-05-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitae', '0007_curso_codificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codificado',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
