# Generated by Django 5.0.5 on 2024-05-11 12:12

import Vitae.models
import django.db.models.deletion
import django_enumfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitae', '0007_curso_acronimo_alter_curso_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('estado', django_enumfield.db.fields.EnumField(default=0, enum=Vitae.models.EstadoSub)),
                ('admin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliado_por', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerido_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
