# Generated by Django 5.0.4 on 2024-05-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vitae', '0008_sugestao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uc',
            name='skills',
        ),
    ]
