# Generated by Django 5.0.4 on 2024-05-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitae', '0010_alter_curso_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='codificado',
        ),
        migrations.AddField(
            model_name='curso',
            name='acronimo',
            field=models.CharField(max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
