# Generated by Django 5.0.4 on 2024-05-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitae', '0013_alter_nota_nota_matricula_unique_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='facebook',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='github',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='instagram',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='morada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
    ]
