# Generated by Django 5.0.4 on 2024-05-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitae', '0014_aluno_facebook_aluno_github_aluno_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
