# Generated by Django 5.0.4 on 2024-05-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitae', '0015_alter_aluno_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
