# Generated by Django 5.0.4 on 2024-04-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='logo',
            field=models.ImageField(null=True, upload_to='categorias'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='imagem',
            field=models.ImageField(null=True, upload_to='comentarios'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
