# Generated by Django 5.0.4 on 2024-05-01 12:29

import Community.models
import django_enumfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0003_categoria_postagens_post_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='grupo',
            field=django_enumfield.db.fields.EnumField(default=1, enum=Community.models.GrupoCategoria),
        ),
    ]
