# Generated by Django 5.0.4 on 2024-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0004_categoria_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='postagens',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comentarios',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='logo',
            field=models.ImageField(blank=True, upload_to='Categorias'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='Comentarios'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='Posts'),
        ),
    ]
