# Generated by Django 5.0.4 on 2024-05-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0006_remove_post_data_remove_post_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='imagem',
            field=models.ImageField(blank=True, default='', upload_to='Comentarios'),
            preserve_default=False,
        ),
    ]
